# Generated by Django 4.2.20 on 2025-06-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akabat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproject',
            name='last_step',
            field=models.CharField(default='welcome', max_length=100),
        ),
    ]
