# Generated by Django 4.2.20 on 2025-06-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akabat_app', '0002_savedproject_last_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproject',
            name='session_csvs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='savedproject',
            name='session_excluded',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='savedproject',
            name='session_included',
            field=models.JSONField(default=dict),
        ),
    ]
